on:
  push:
  workflow_dispatch:
  # Run at 9:23pm Monday-Friday
  schedule: [{cron: '23 21 * * 1-5'}]

name: scrape

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true
    - uses: r-lib/actions/setup-r-dependencies@v2

    - name: Fetch latest data
      run: Rscript scrape.R

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: By action https://github.com/${{ env.GITHUB_REPOSITORY }}/actions/runs/${{ env.GITHUB_RUN_ID }}

  collapse:
    needs: scrape
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true
    - uses: r-lib/actions/setup-r-dependencies@v2

    - name: Collapse into yearly parquet files
      run: Rscript collapse.R

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: By action https://github.com/${{ env.GITHUB_REPOSITORY }}/actions/runs/${{ env.GITHUB_RUN_ID }}
